import type { Metadata, Viewport } from 'next';
import Header from '../components/Header';
import Footer from '../components/Footer';
import AnalyticsConsent from '../components/AnalyticsConsent';
import { AdContentEnd, AdStickyBanner } from '../components/Ads';
import './globals.css';
export const metadata:Metadata={metadataBase:new URL('https://fcgallery.wiki'),title:{default:'FC 27 Gallery Calculator & Route Planner | FCGallery',template:'%s | FCGallery'},description:'Plan your FC 27 Gallery upgrades. Compare coin loss, trading capital and transactions, or check item scores and bonus tags.',openGraph:{title:'FCGallery route planner',description:'Compare Gallery upgrade options and check your Set scores.',siteName:'FCGallery',images:[{url:'https://fcgallery.wiki/og.png',width:1200,height:630,alt:'FCGallery collection route planner'}]},twitter:{card:'summary_large_image',title:'FCGallery route planner',description:'Compare Gallery upgrade options and check your Set scores.',images:['https://fcgallery.wiki/og.png']},icons:{icon:[{url:'/favicon-16x16.png',sizes:'16x16',type:'image/png'},{url:'/favicon-32x32.png',sizes:'32x32',type:'image/png'}],apple:[{url:'/favicon-180x180.png',sizes:'180x180'}]},robots:{index:true,follow:true}};
export const viewport:Viewport={width:'device-width',initialScale:1,themeColor:[{media:'(prefers-color-scheme: light)',color:'#f4f6fb'},{media:'(prefers-color-scheme: dark)',color:'#101728'}]};
const themeBoot="try{var t=localStorage.getItem('fcgallery-theme');document.documentElement.dataset.theme=t==='dark'||(!t&&matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light'}catch(e){}";
export default function Layout({children}:{children:React.ReactNode}){return <html lang="en" suppressHydrationWarning><head><link rel="preload" href="/fonts/manrope.woff2" as="font" type="font/woff2" crossOrigin="anonymous"/><script dangerouslySetInnerHTML={{__html:themeBoot}}/></head><body><a className="skip-link" href="#main">Skip to content</a><Header/>{children}<AdContentEnd/><Footer/><AdStickyBanner/><AnalyticsConsent/></body></html>}
