'use client';
import Link from '@/components/SiteLink';
import { useEffect, useRef, useState } from 'react';
import { usePathname } from 'next/navigation';
function Icon({kind}:{kind:'route'|'score'|'guide'|'sun'|'moon'}) {return <svg data-nav-icon={kind} width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true">{kind==='route'?<><path d="M5 5h14v14H5zM9 9h6M9 13h6M9 17h3"/></>:kind==='score'?<><path d="M4 20V10h4v10m4 0V4h4v16m4 0H2"/></>:kind==='guide'?<><path d="M12 5c-4-3-9-2-9-2v16s5-1 9 2c4-3 9-2 9-2V3s-5-1-9 2zM12 5v16"/></>:kind==='sun'?<><circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/></>:<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11z"/>}</svg>}
const menus=[{name:'Tools',icon:'score' as const,links:[['Route planner','/'],['Score calculator','/gallery-score-calculator/']]},{name:'Gallery',icon:'guide' as const,links:[['Levels & rewards','/gallery-levels/'],['First Owner bonus','/first-owner-bonus/'],['How Gallery works','/gallery-guide/']]}];
export default function Header(){
 const [open,setOpen]=useState<string|null>(null);const [mobile,setMobile]=useState(false);const [dark,setDark]=useState(false);const ref=useRef<HTMLElement>(null);const path=usePathname();
 useEffect(()=>{const sync=()=>setDark(document.documentElement.dataset.theme==='dark');sync();const observer=new MutationObserver(sync);observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});return()=>observer.disconnect();},[]);
 useEffect(()=>{const click=(event:PointerEvent)=>{if(!ref.current?.contains(event.target as Node)){setOpen(null);setMobile(false)}};const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setOpen(null);setMobile(false);(ref.current?.querySelector('[aria-expanded="true"]') as HTMLElement|null)?.focus()}};document.addEventListener('pointerdown',click);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',click);document.removeEventListener('keydown',key)}},[]);
 const toggle=()=>{const next=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=next?'dark':'light';try{localStorage.setItem('fcgallery-theme',next?'dark':'light')}catch{}setDark(next)};
 return <header className="site-header" ref={ref}><div className="header-inner"><Link className="brand" href="/" aria-label="FCGallery home"><img src="/favicon-64x64.png" width="32" height="32" alt=""/><span>FCGallery</span></Link><button className="mobile-menu icon-button" aria-label="Toggle navigation" aria-expanded={mobile} aria-controls="main-navigation" onClick={()=>setMobile(!mobile)}><svg viewBox="0 0 24 24" width="22" height="22" stroke="currentColor" fill="none" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button><nav id="main-navigation" className={'main-navigation'+(mobile?' mobile-open':'')} aria-label="Main navigation"><Link href="/" data-nav-item="route" className={'nav-item'+(path==='/'?' active':'')} onClick={()=>{setMobile(false);setOpen(null)}}><Icon kind="route"/>Planner</Link>{menus.map(menu=><div className="nav-group" key={menu.name}><button data-nav-item={menu.icon} className="nav-item" aria-expanded={open===menu.name} aria-controls={'menu-'+menu.name} onClick={()=>setOpen(open===menu.name?null:menu.name)}><Icon kind={menu.icon}/>{menu.name}<svg className="chevron" viewBox="0 0 12 12" width="12" height="12" aria-hidden="true"><path d="m2 4 4 4 4-4" stroke="currentColor" fill="none"/></svg></button><div id={'menu-'+menu.name} className="dropdown" hidden={open!==menu.name}>{menu.links.map(([label,href])=><Link href={href} key={href} aria-current={path===href?'page':undefined} onClick={()=>{setOpen(null);setMobile(false)}}>{label}</Link>)}</div></div>)}</nav><button data-nav-item={dark?'sun':'moon'} className="theme-toggle icon-button" onClick={toggle} aria-label={dark?'Switch to light theme':'Switch to dark theme'} title={dark?'Light theme':'Dark theme'}><Icon kind={dark?'sun':'moon'}/></button></div></header>
}
